---
- hosts: hub-sw1.lab.local
  vars:
    output_dir: results
    ios_commands:
      - show ip interface

  roles:
    - ansible-network.network-engine

  tasks:
    - name: "Clear results directory"
      local_action: file path={{ output_dir }} state=absent
      changed_when: false
      run_once: true

    - name: "Create results folder structure"
      local_action: file path={{ output_dir }} state=directory
      changed_when: false
      run_once: true

    - name: "Gather data via show command"
      ios_command:
        commands: "{{ ios_commands }}"
      register: command_output

    - name: "Apply TextFSM template"
      textfsm_parser:
        file: "./textfsm-templates/cisco_ios_show_ip_interface.template"
        content: "{{ command_output.stdout[0] }}"
        name: ip_interface_facts 

    # - name: "Debug ip routes"
    #   debug:
    #     var: ansible_facts.ip_interface_facts

    - name: "Generating Huawei interface vlan configuration"
      template: src=./j2-templates/huawei-svi.j2 dest=./{{ output_dir }}/{{ inventory_hostname }}-svi.cfg

